apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssm-backend-deployment
  labels:
    app: ssm-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssm-api
  template:
    metadata:
      labels:
        app: ssm-api
    spec:
      containers:
      - name: ssm-backend-container
        image: ssm-backend:latest 
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          # 丘멆잺 REEMPLAZAR: Cadena de conexi칩n real de MongoDB Atlas
          value: "mongodb+srv://esteban01cortes:cortespassword@clustersmt.27xywuz.mongodb.net/?retryWrites=true&w=majority&appName=ClusterSMT"
        
        # 游 NUEVA SECCI칍N: Definici칩n de recursos (para eliminar la advertencia)
        resources:
          requests:
            cpu: "100m"     # Solicita 0.1 de un n칰cleo
            memory: "128Mi" # Solicita 128 Megabytes
          limits:
            cpu: "200m"     # L칤mite m치ximo de 0.2 de un n칰cleo
            memory: "256Mi" # L칤mite m치ximo de 256 Megabytes
            
        imagePullPolicy: Never 
